# ==============================================
# MODULETRADE DOCKER-COMPOSE CONFIGURATION
# ==============================================

services:
  # ==============================================
  # POSTGRESQL DATABASE
  # ==============================================
  postgres:
    image: postgres:15-alpine
    container_name: moduletrade_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-saas_platform}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-594YqJoG2Vo0u6bYry732oZ_Q}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    networks:
      - moduletrade-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-saas_platform}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    command: >
      postgres
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200

  # ==============================================
  # REDIS CACHE
  # ==============================================
  redis:
    image: redis:7-alpine
    container_name: moduletrade_redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-d-g-6u--aD-kGQGbm3LRaKOBp}
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD:-d-g-6u--aD-kGQGbm3LRaKOBp}
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
      --appendonly yes
      --appendfsync everysec
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - moduletrade-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  # ==============================================
  # RABBITMQ MESSAGE BROKER
  # ==============================================
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: moduletrade_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-moduletrade_admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-3mVVdqZ9EcyrpQSCS-c44r7yV}
      RABBITMQ_DEFAULT_VHOST: moduletrade
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - moduletrade-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  # ==============================================
  # BACKEND API
  # ==============================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-production}
    container_name: moduletrade_backend
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 3000

      # Database
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB:-saas_platform}
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-594YqJoG2Vo0u6bYry732oZ_Q}

      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-d-g-6u--aD-kGQGbm3LRaKOBp}

      # RabbitMQ
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-moduletrade_admin}:${RABBITMQ_PASS:-3mVVdqZ9EcyrpQSCS-c44r7yV}@rabbitmq:5672/moduletrade

      # JWT
      JWT_SECRET: ${JWT_SECRET:-VerySecureJWTSecretKeyForModuleTradeProject2025MinimumLength32Characters}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-AnotherSecureJWTRefreshKeyForModuleTradeProject2025DifferentFromMain}

      # API URLs
      API_URL: ${API_URL:-https://api.moduletrade.ru}
      FRONTEND_URL: ${FRONTEND_URL:-https://moduletrade.ru}

      # CORS Configuration
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:8080,http://localhost:3000,https://moduletrade.ru,https://www.moduletrade.ru}

      # Other
      LOG_LEVEL: ${LOG_LEVEL:-info}
      UPLOAD_DIR: ./uploads
    volumes:
      - backend_uploads:/app/uploads
      - backend_logs:/app/logs
    ports:
      - "3000:3000"
    networks:
      - moduletrade-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  # ==============================================
  # FRONTEND REACT APP
  # ==============================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-https://api.moduletrade.ru/api}
        REACT_APP_STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY:-}
    container_name: moduletrade_frontend
    ports:
      - "8080:80"
    networks:
      - moduletrade-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # ==============================================
  # NGINX REVERSE PROXY
  # ==============================================
  nginx:
    image: nginx:alpine
    container_name: moduletrade_nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
       - ./nginx/conf.d:/etc/nginx/conf.d:ro
       - ./nginx/certs:/etc/nginx/certs:ro
       - ./nginx/api_cors.conf:/etc/nginx/api_cors.conf:ro
       - nginx_logs:/var/log/nginx
    networks:
      - moduletrade-network
    depends_on:
      - backend
      - frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

# ==============================================
# DOCKER VOLUMES
# ==============================================
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local
  backend_uploads:
    driver: local
  backend_logs:
    driver: local
  nginx_logs:
    driver: local

# ==============================================
# DOCKER NETWORKS
# ==============================================
networks:
  moduletrade-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16